language: node_js

node_js:
  - node

before_script:
  - npm install -g codeclimate-test-reporter
  - psql -c 'drop database if exists youdoc_test;' -U postgres
  - psql -c 'create database youdoc_test;' -U postgres
  - NODE_ENV=test npm run migrate

services:
  - postgresql

script:
  - npm test

after_success:
  -   CODECLIMATE_REPO_TOKEN=8adecf4f9449fd785530664a08ab466aa6512bf386ebae1ac3d8579f5fc79209 codeclimate-test-reporter < coverage/lcov.info
